
on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

name: Main workflow

env:
  # ETHERSCAN_TOKEN:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # WEB3_INFURA_PROJECT_ID:

  # increasing available memory for node reduces issues with ganache crashing
  # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
  NODE_OPTIONS: --max_old_space_size=4096

jobs:

  contract-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Compiler Installations
      uses: actions/cache@v2
      with:
        path: |
          ~/.solcx
          ~/.vvm
        key: compiler-cache

    - name: Setup Node.js
      uses: actions/setup-node@v2

    - name: Install Ganache
      run: npm install -g ganache-cli@6.12.2

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pipx, ensurepath and brownie
      run: |
         python -m pip install --user pipx
         python -m pipx ensurepath
         pipx install eth-brownie

    - name: Add network
      run: brownie networks add Development "harmony-fork" host=http://127.0.0.1 cmd=ganache-cli fork=https://a.api.s0.t.hmny.io port=8545 chain_id=1666600000

    - name: Run Tests
      run: brownie test --network harmony-fork --verbose --gas --coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: coverage-report
        # A file, directory or wildcard pattern that describes what to upload
        path: reports/coverage.json
        # The desired behavior if no files are found using the provided path.
